version: '3.4'

services:
  b2h.materialslist.api:
    hostname: materialslist-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=8081
      - POSTGRESS_CONNECTINGSTRING=${POSTGRESS_CONNECTINGSTRING}
      - CONNECTINGSTRING=${MATERIALS_CONNECTINGSTRING}
    ports:
      - "8090:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    restart: unless-stopped

  b2h.materialslist.api.webstorage:
    hostname: materialslist-us
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - SOURCE_STORAGE=/home/
      - CONNECTINGSTRING=${FILEBASE_CONNECTINGSTRING}
      - URL_IDETITYSERVER=${URL_IDENTITYSERVER}
    ports:
      - "8085:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    restart: unless-stopped

  b2h.materialslist.webui:
    hostname: materialslist-ui
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  
  proxy:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    ports:
      - "80:80"

  database:
    container_name: "app-database"
    hostname: database
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password12!
    expose:
     - "1433"
    ports:
      - "1433:1433"
    restart: unless-stopped
    volumes:
       - ./database:/var/opt/mssql/data
  
  db-postgres:
    command:
        - "postgres"
        - "-c"
        - "config_file=/etc/postgresql.conf"
    environment:
        POSTGRES_DB: "B2HMaterials"
        POSTGRES_USER: "b2h"
        POSTGRES_PASSWORD: "temppgpwd4"
        PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
       - ./pginitdata:/docker-entrypoint-initdb.d
       - ./pgdata/postgresql.conf:/etc/postgresql.conf:ro
    ports:
        - "1434:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U b2h -d B2HMaterials"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 82:80
      - 5341:5341 
    restart: unless-stopped

