version: '3.4'
volumes:
  db:
    name: db
    driver: local
    driver_opts:
      o: bind
      type: volume
      device: /mnt/c/Users/unist/Documents/WebMaterials/materialslist/database/
  source:
    name: source
    driver: local
    driver_opts:
      o: bind 
      type: volume
      device: ./Source
services:
  materialslist-backend:
    container_name: backend
    image: b2h.cr.cloud.ru/materialslist/backend
    build:
      context: ..
      dockerfile: materialslist-backend/Dockerfile

  materialslist-ui:
    container_name: ui
    image: b2h.cr.cloud.ru/materialslist/ui:latest
    build:
      context: ../materialslist-ui/
      dockerfile: ../materialslist-ui/Dockerfile


  materialslist-us:
    container_name: us
    image: b2h.cr.cloud.ru/materialslist/us
    build:
      context: ..
      dockerfile: materialslist-us/Dockerfile

  proxy:
    container_name: nginx
    image: nginx:latest
    depends_on:
      - materialslist-ui
  database:
    container_name: "app-database"
    hostname: database
    image: mcr.microsoft.com/mssql/server:2019-latest

  identityserver:
    image: b2h.cr.cloud.ru/identityserver
    build:
      context: .
      dockerfile: B2H.IdentityServer/Dockerfile

