networks:
  front:
    driver: bridge
  back:
    driver: bridge

services:
  database:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD= ${PASSWORD_MSDATABASE}
      - URL_MATERIALSAPI = ${URL_MATERIALSAPI}
      - URL_FILESAPI = ${URL_FILESAPI}
    expose:
     - "1433"
    ports:
      - "1433:1433"
    restart: always
    networks:
      - back
    volumes:
       - ./database:/var/opt/mssql/data
  
  materialslist-backend:
    hostname: backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    depends_on:
      - database
    ports:
      - "8090:8080"
      - "8091:8081"
    restart: always
    networks:
      - back
      - front
    volumes:
      - ${USERS_SECRETS_WIND}:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  materialslist-ui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    depends_on:
      - materialslist-backend
      - materialslist-us
    restart: always
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - front
    volumes:
      - ${USERS_SECRETS_WIND}:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
 
  materialslist-us:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - SOURCE_STORAGE=/home/
    ports:
      - "8085:8080"
      - "8086:8081"
    networks:
      - back
      - front
    volumes:
      - ${USERS_SECRETS_WIND}:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${FILEBASE_SOURCE_DIR}:/home/Source

  proxy:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - front
