version: '3.4'
networks:
  front:
    driver: bridge
  back:
    driver: bridge
volumes:
  db:
    name: db
    driver: local
    driver_opts:
      o: bind
      type: volume
      device: ./database
  source:
    name: db
    driver: local
    driver_opts:
      o: bind 
      type: volume
      device: ../materialslist-us/Source/
services:
  database:
    container_name: "app-database"
    hostname: database
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password12!
    expose:
     - "1433"
    ports:
      - "1433:1433"
    volumes:
       - db:/var/opt/mssql/data
    restart: always
    networks:
      - back
  materialslist-backend:
    hostname: backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8090
    depends_on:
      - database
    ports:
      - "8090:8090"
    restart: always
    networks:
      - back
      - front

  materialslist-ui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    depends_on:
      - materialslist-backend
      - materialslist-us
    restart: always
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - front
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  materialslist-us:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8085:8080"
      - "8086:8081"
    networks:
      - back
      - front
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - source:/app/source
  proxy:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    ports:
      - "80:80"
    depends_on:
      - materialslist-ui
    networks:
      - front