version: '3.4'

services:
  b2h.materialslist.api:
    container_name: backend
    image: ${DOCKER_REGISTRY-}b2h.cr.cloud.ru/materialslist/backend:develop
    build:
      context: .
      dockerfile: B2H.MaterialsList.API/Dockerfile

  b2h.materialslist.api.webstorage:
    image: b2h.cr.cloud.ru/materialslist/us:develop
    build:
      context: .
      dockerfile: B2H.MaterialsList.API.WebStorage/Dockerfile


  b2h.materialslist.webui:
    container_name: ui
    image: b2h.cr.cloud.ru/materialslist/ui:develop
    build:
      context: .
      dockerfile: B2H.MaterialsList.WebUI/Dockerfile
    depends_on:
    - database
    - db-postgres
    - b2h.materialslist.api
  
  proxy:
    container_name: nginx
    image: nginx:latest
    depends_on:
      - b2h.materialslist.webui
  
  database:
    container_name: "app-database"
    hostname: database
    image: mcr.microsoft.com/mssql/server:2019-latest

  db-postgres:
    image: postgres:16.1-alpine3.18
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
  
  seq:
    container_name: serilog
    image: datalust/seq
  