
networks:
  front:
    driver: bridge
  back:
    driver: bridge
volumes:
  is-www:
    driver: local  
  ui-www:
    driver: local
services:
  
  materialslist-backend:
    hostname: backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - CONNECTINGSTRING=${MATERIALS_CONNECTINGSTRING}
    ports:
      - "8090:8080"
    restart: always
    networks:
      - back
      - front

  materialslist-ui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=8081
      - URL_IDENTITYSERVER=${URL_IDENTITYSERVER}
      - URL_FILESAPI=${URL_FILESAPI}
      - URL_MATERIALSAPI=${URL_MATERIALSAPI}
      - URL_METADATE_IDENTITYSERVER=${URL_METAIS}
    restart: always
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - front
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ui-www:/app/wwwroot
 
  materialslist-us:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - SOURCE_STORAGE=/home/
      - CONNECTINGSTRING=${FILEBASE_CONNECTINGSTRING}
      - URL_IDETITYSERVER=${URL_IDENTITYSERVER}
    ports:
      - "8085:8080"
    networks:
      - back
      - front
    volumes:
      - ${FILEBASE_SOURCE_DIR}:/home/Source

  proxy:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ui-www:/etc/nginx/ui-www/
    restart: always
    ports:
      - "80:80"
    networks:
      - front
      - back

  database:
    container_name: "app-database"
    hostname: database
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password12!
    expose:
     - "1433"
    ports:
      - "1433:1433"
    restart: always
    networks:
      - back
    volumes:
       - ./database:/var/opt/mssql/data

  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 82:80
      - 5341:5341 
    restart: unless-stopped
    networks:
      - back
  # identityserver:
    # environment:
    #   - ASPNETCORE_ENVIRONMENT=Development
    #   - ASPNETCORE_HTTP_PORTS=8080
    #   # - ASPNETCORE_HTTPS_PORTS=8081
    # ports:
    #   - "5000:8080"
    #   - "5001:8081"
    # volumes:
    #   - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    #   - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    #   - is-www:/app/wwwroot
    # networks:
    #   - back
    #   - front