version: '3.4'

services:
  materialslist-backend:
    container_name: backend
    image: materialslist/backend
    build:
      context: ..
      dockerfile: materialslist-backend/Dockerfile

  materialslist-ui:
    container_name: ui
    image: materialslist/ui
    build:
      context: ../materialslist-ui/
      dockerfile: ../materialslist-ui/Dockerfile


  materialslist-us:
    container_name: us
    image: materialslist/us
    build:
      context: ..
      dockerfile: materialslist-us/Dockerfile

  proxy:
    container_name: nginx
    image: nginx:latest
    depends_on:
      - materialslist-ui
  database:
    container_name: "app-database"
    hostname: database
    image: mcr.microsoft.com/mssql/server:2019-latest

  
