version: '3.4'
networks:
  front:
    driver: bridge
  back:
    driver: bridge

services:
  database:
    container_name: "app-database"
    hostname: database
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password12!
    expose:
     - "1433"
    ports:
      - "1433:1433"
    restart: always
    networks:
      - back
    volumes:
       - ./database:/var/opt/mssql/data
  
  materialslist-backend:
    hostname: backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8090
    depends_on:
      - database
    ports:
      - "8090:8090"
    restart: always
    networks:
      - back
      - front

  materialslist-ui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    depends_on:
      - materialslist-backend
      - materialslist-us
    restart: always
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - front
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
 
  materialslist-us:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8085:8080"
    networks:
      - back
      - front
    volumes:
      - ${FILEBASE_SOURCE_DIR}:/home/Source

  proxy:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    ports:
      - "80:80"
    depends_on:
      - materialslist-ui
    networks:
      - front

  b2h.identityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
