version: '3.4'

services:
  materialslist-backend:
    container_name: backend
    image: ${DOCKER_REGISTRY-}materialslistbackend
    build: ../materialslist-backend

  materialslist-ui:
    container_name: ui
    image: ${DOCKER_REGISTRY-}materialslistui
    build: ../materialslist-ui


  materialslist-us:
    container_name: us
    image: ${DOCKER_REGISTRY-}materialslistus
    build: ../materialslist-us

  proxy:
    container_name: nginx
    image: nginx:latest
    depends_on:
      - materialslist-ui
  database:
    container_name: "app-database"
    hostname: database
    image: mcr.microsoft.com/mssql/server:2019-latest

  
