
services:
  materialslist-backend:
    container_name: backend
    image: b2h.cr.cloud.ru/materialslist/backend:test
    depends_on:
      - database
    build:
      # context: ..
      dockerfile: ../materialslist-backend/Dockerfile

  materialslist-ui:
    container_name: ui
    image: b2h.cr.cloud.ru/materialslist/ui:test
    depends_on:
      - materialslist-backend
      - materialslist-us
    build:
      context: ../materialslist-ui/
      dockerfile: ../materialslist-ui/Dockerfile

  materialslist-us:
    container_name: us
    image: b2h.cr.cloud.ru/materialslist/us:test
    build:
      # context: ..
      dockerfile: ../materialslist-us/Dockerfile

  proxy:
    container_name: nginx
    image: nginx:latest
    depends_on:
      - materialslist-ui
  
  database:
    container_name: "app-database"
    hostname: database
    image: mcr.microsoft.com/mssql/server:2019-latest

  seq:
    container_name: serilog
    image: datalust/seq
  # identityserver:
  #   container_name: "identityserver"
  #   image: b2h.cr.cloud.ru/identityserver:test
  #   build:
  #     context: .
  #     dockerfile: B2H.IdentityServer/Dockerfile
