version: '3.4'
networks:
  front:
    driver: bridge
  back:
    driver: bridge
services:
  database:
    container_name: "app-database"
    hostname: database
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password12!
    expose:
     - "1433"
    ports:
      - "1433:1433"
    volumes:
       - ./database:/var/opt/mssql/data
    restart: always
    networks:
      - back
  materialslist-backend:
    hostname: backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8090
    ports:
      - "8090"
    networks:
      - back
      - front

  materialslist-ui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - front
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
